// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAst0qnDNG0ApWiW-FGZGgGKbF1oGgkHg0',
    appId: '1:114031383420:web:a5774e493f19ed3e438af9',
    messagingSenderId: '114031383420',
    projectId: 'freelance-f81fc',
    authDomain: 'freelance-f81fc.firebaseapp.com',
    databaseURL: 'https://freelance-f81fc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'freelance-f81fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEbJ_tTLY9LG5CzRfsB-UZ6H1_fZEhOM0',
    appId: '1:114031383420:android:7596cbaa1261e55f438af9',
    messagingSenderId: '114031383420',
    projectId: 'freelance-f81fc',
    databaseURL: 'https://freelance-f81fc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'freelance-f81fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxfFag9tYgoUCnHdfvh92X0Ws4yPnKNlU',
    appId: '1:114031383420:ios:06624b85dcaa7f05438af9',
    messagingSenderId: '114031383420',
    projectId: 'freelance-f81fc',
    databaseURL: 'https://freelance-f81fc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'freelance-f81fc.firebasestorage.app',
    iosBundleId: 'com.example.freelance5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxfFag9tYgoUCnHdfvh92X0Ws4yPnKNlU',
    appId: '1:114031383420:ios:06624b85dcaa7f05438af9',
    messagingSenderId: '114031383420',
    projectId: 'freelance-f81fc',
    databaseURL: 'https://freelance-f81fc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'freelance-f81fc.firebasestorage.app',
    iosBundleId: 'com.example.freelance5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAst0qnDNG0ApWiW-FGZGgGKbF1oGgkHg0',
    appId: '1:114031383420:web:0ea643b54b3a90ef438af9',
    messagingSenderId: '114031383420',
    projectId: 'freelance-f81fc',
    authDomain: 'freelance-f81fc.firebaseapp.com',
    databaseURL: 'https://freelance-f81fc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'freelance-f81fc.firebasestorage.app',
  );

}